export const BOOK_CREATE_REQUEST = "BOOK_CREATE_REQUEST";
export const BOOK_CREATE_SUCCESS = "BOOK_CREATE_SUCCESS";
export const BOOK_CREATE_FAIL = "BOOK_CREATE_FAIL";
export const BOOK_CREATE_RESET = "BOOK_CREATE_RESET";

export const BOOK_LIST_MY_REQUEST = "BOOK_LIST_MY_REQUEST";
export const BOOK_LIST_MY_SUCCESS = "BOOK_LIST_MY_SUCCESS";
export const BOOK_LIST_MY_FAIL = "BOOK_LIST_MY_FAIL";
export const BOOK_LIST_MY_RESET = "BOOK_LIST_MY_RESET";

export const BOOK_CANCELED_REQUEST = "BOOK_CANCELED_REQUEST";
export const BOOK_CANCELED_SUCCESS = "BOOK_CANCELED_SUCCESS";
export const BOOK_CANCELED_FAIL = "BOOK_CANCELED_FAIL";
export const BOOK_CANCELED_RESET = "BOOK_CANCELED_RESET";